import type { ReactElement } from 'react'
import type { IconProps } from './Icon.tsx'

export type IconName =
  | 'home'
  | 'homeFill'
  | 'quests'
  | 'questsFill'
  | 'rewards'
  | 'rewardsFill'
  | 'trophy'
  | 'trophyFill'
  | 'user'
  | 'userFill'
  | 'book'
  | 'flame'
  | 'flameFill'
  | 'check'
  | 'plus'
  | 'chevR'
  | 'chevL'
  | 'chevD'
  | 'close'
  | 'settings'
  | 'bell'
  | 'star'
  | 'starFill'
  | 'clock'
  | 'sparkle'
  | 'lock'
  | 'pages'
  | 'shield'
  | 'heart'
  | 'arrowUp'
  | 'camera'
  | 'calendar'
  | 'bolt'
  | 'gift'
  | 'trash'
  | 'edit'
  | 'target'
  | 'hourglass'
  | 'moon'
  | 'pencilSquare'

export type IconComponent = (props: IconProps) => ReactElement
